apiVersion: apps/v1
kind: Deployment
metadata:
  name: nl2sql-api
  labels:
    app: nl2sql-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nl2sql-api
  template:
    metadata:
      labels:
        app: nl2sql-api
    spec:
      containers:
      - name: nl2sql-api
        image: nl2sql-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: NL2SQL_API_KEY
          valueFrom:
            secretKeyRef:
              name: nl2sql-secrets
              key: api-key
        - name: PORT
          value: "8000"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nl2sql-api-service
spec:
  selector:
    app: nl2sql-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: nl2sql-secrets
type: Opaque
data:
  api-key: eW91ci1zZWN1cmUtYXBpLWtleS1oZXJl  # base64 encoded 